import React,{useEffect,useState,lazy,Suspense,useRef} from 'react'
import {createRoot} from 'react-dom/client'
import {ResponsiveContainer,LineChart,Line} from 'recharts'
import './styles.css'
const PriceChart=lazy(()=>import('./components/PriceChart.jsx'))
const EquityChart=lazy(()=>import('./components/EquityChart.jsx'))
const TradeLog=lazy(()=>import('./components/TradeLog.jsx'))
const Diagnostics=lazy(()=>import('./components/Diagnostics.jsx'))
const Alerts=lazy(()=>import('./components/Alerts.jsx'))

const Skeleton=({h=120})=><div className="skeleton" style={{height:h}}/>
async function getJSON(path){const r=await fetch(path); if(!r.ok) throw Error(await r.text()); return r.json()}
function Metric({label,value,trend}){return <div className="metric"><span>{label}</span><b>{value??'—'}</b>{trend&&<small>{trend}</small>}</div>}
function useNearViewport(rootMargin='200px'){const ref=useRef(null);const [visible,setVisible]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const io=new IntersectionObserver(([e])=>{if(e.isIntersecting){setVisible(true);io.disconnect()}},{rootMargin});io.observe(el);return()=>io.disconnect()},[rootMargin]);return [ref,visible]}
function LazyPanel({children,height=300}){const [ref,visible]=useNearViewport();return <div ref={ref}>{visible?children:<Skeleton h={height}/>}</div>}
function App(){
 const [mode,setMode]=useState('PAPER_TESTNET'); const [pendingMode,setPendingMode]=useState(null); const [overview,setOverview]=useState(null); const [metrics,setMetrics]=useState(null); const [history,setHistory]=useState([]); const [error,setError]=useState('')
 useEffect(()=>{let dead=false;(async()=>{try{const [o,m,h]=await Promise.all([getJSON('/api/overview?mode='+mode),getJSON('/api/metrics?mode='+mode),getJSON('/api/metric-history?mode='+mode)]);if(!dead){setOverview(o);setMetrics(m);setHistory(h.rows||[])}}catch(e){setError(e.message)}})();return()=>{dead=true}},[mode])
 useEffect(()=>{let ws; let retry; const lastSeq={}; const connect=()=>{ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws/live');ws.onopen=()=>ws.send(JSON.stringify({type:'subscribe',modes:[mode],symbols:['BTCUSDT']}));ws.onmessage=e=>{const x=JSON.parse(e.data); const ch=x.channel||x.type; const scopeKey=`${ch}|${x.mode||''}|${x.symbol||''}`; if(typeof x.seq==='number'){const prev=lastSeq[scopeKey]; if(prev!=null && x.seq!==prev+1){ws.send(JSON.stringify({type:x.channel==='market_tick'?'market_resync':'resync',mode:x.mode||mode,symbol:x.symbol||'BTCUSDT'})); lastSeq[scopeKey]=x.seq; return} lastSeq[scopeKey]=x.seq} if((x.type==='state_snapshot'||x.type==='execution_state_delta'||x.type==='overview_delta')&&x.mode===mode){setOverview(x.type==='state_snapshot'?x.data:prev=>({...prev,...x.data}))} else if((x.type==='market_tick'||x.type==='market_snapshot')&&x.symbol==='BTCUSDT'){setOverview(prev=>prev?({...prev,last_market_tick:x}):prev)}};ws.onclose=()=>{retry=setTimeout(connect,1500)}};connect();return()=>{clearTimeout(retry);ws?.close()}},[mode])
 const paper=mode!=='LIVE';
 return <div className="app"><header><div><h1>Crypto RL Trader</h1><p>Execution, model and risk telemetry</p></div><div className={'mode '+(paper?'paper':'live')}><span/> {paper?'PAPER / TESTNET':'LIVE'} <select value={mode} onChange={e=>{const next=e.target.value;if(next==='LIVE'&&mode!=='LIVE')setPendingMode('LIVE');else setMode(next)}}><option value="PAPER_TESTNET">Paper / Testnet</option><option value="LIVE">Live</option></select></div></header>
 {error&&<div className="alert danger">API error: {error}</div>}
 <main>
 <section className="overview-grid"><Card title="Live Overview"><div className="metrics-grid"><Metric label="Wallet balance" value={fmt(overview?.wallet_balance)}/><Metric label="Equity" value={fmt(overview?.equity)}/><Metric label="Unrealized PnL" value={fmt(overview?.unrealized_pnl)}/><Metric label="Today PnL" value={fmt(overview?.today_pnl)}/><Metric label="Leverage" value={overview?.leverage?overview.leverage+'x':'—'}/><Metric label="Margin ratio" value={fmtPct(overview?.margin_ratio)}/><Metric label="Trades today" value={overview?.today_trade_count}/><Metric label="Available balance" value={fmt(overview?.available_balance)}/><Metric label="Maintenance margin" value={fmt(overview?.total_maint_margin)}/><Metric label="Initial margin" value={fmt(overview?.total_initial_margin)}/><Metric label="Mark price" value={fmt(overview?.funding?.mark_price)}/><Metric label="Index price" value={fmt(overview?.funding?.index_price)}/></div><div className="health"><b>WS</b><span className={overview?.connection?.ws?'ok':'bad'}>{overview?.connection?.ws?'Connected':'Disconnected'}</span><b>Heartbeat</b><span>{overview?.connection?.last_heartbeat?new Date(overview.connection.last_heartbeat).toLocaleTimeString():'—'}</span><b>Reconciliation</b><span className={overview?.connection?.reconciliation_ok?'ok':'bad'}>{overview?.connection?.reconciliation_ok===true?'OK':overview?.connection?.reconciliation_ok===false?'MISMATCH':'—'}</span></div></Card><Card title="Open Positions"><div className="positions">{(overview?.open_positions||[]).length?<table><thead><tr><th>Symbol</th><th>Qty</th><th>Entry</th><th>uPnL</th><th>Mark</th><th>Liq</th></tr></thead><tbody>{overview.open_positions.map(p=><tr key={p.symbol}><td>{p.symbol}</td><td>{p.qty}</td><td>{p.entry_price}</td><td>{fmt(p.unrealized_pnl)}</td><td>{fmt(p.mark_price)}</td><td>{fmt(p.liquidation_price)}</td></tr>)}</tbody></table>:<div className="empty">No open positions</div>}</div></Card></section>
 <section className="grid"><Card title="Equity Curve & Drawdown" wide><Suspense fallback={<Skeleton h={340}/>}><EquityChart mode={mode}/></Suspense></Card><Card title="Risk Panel"><Risk overview={overview}/></Card></section>
 <section className="grid"><Card title="Price & Signals" wide><Suspense fallback={<Skeleton h={360}/>}><PriceChart mode={mode} symbol="BTCUSDT"/></Suspense></Card><Card title="Performance Metrics"><div className="metrics-grid one">{metrics&&Object.entries(metrics).filter(([k])=>['sharpe','sortino','calmar','max_drawdown','win_rate','profit_factor','expectancy','trade_count','average_holding_minutes'].includes(k)).map(([k,v])=><div key={k}><Metric label={label(k)} value={typeof v==='number'?v.toFixed(3):v}/><Sparkline rows={history} metric={k}/></div>)}</div></Card></section>
 <section className="grid"><Card title="Trade Log" wide><Suspense fallback={<Skeleton h={500}/>}><LazyPanel height={500}><TradeLog mode={mode} enabled/></LazyPanel></Suspense></Card><Card title="Alerts / Logs"><LazyPanel height={420}><Suspense fallback={<Skeleton h={420}/>}><Alerts mode={mode} enabled/></Suspense></LazyPanel></Card></section>
 <section className="grid lazy"><Card title="Model / Training Diagnostics" wide><Suspense fallback={<Skeleton h={300}/>}><LazyPanel height={300}><Diagnostics enabled/></LazyPanel></Suspense></Card><Card title="Backtest / Benchmark"><LazyPanel height={180}><Benchmark mode={mode} enabled/></LazyPanel></Card></section>
 </main>{pendingMode === 'LIVE' && <LiveConfirm onCancel={()=>setPendingMode(null)} onConfirm={()=>{setMode('LIVE');setPendingMode(null)}}/>}</div>
}
function Sparkline({rows,metric}){const data=(rows||[]).map((r,i)=>({i,value:r[metric]})).filter(x=>typeof x.value==='number'&&Number.isFinite(x.value));return data.length>1?<ResponsiveContainer width="100%" height={42}><LineChart data={data}><Line type="monotone" dataKey="value" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer>:null}
function Card({title,children,wide}){return <article className={'card '+(wide?'wide':'')}><h2>{title}</h2>{children}</article>}
function Risk({overview}){const m=overview?.risk?.metrics||{},f=overview?.funding||{}; return <div className="risk"><Metric label="Risk state" value={overview?.risk?.allowed===false?'PAUSED':'ALLOWED'}/><Metric label="Daily loss" value={m.daily_loss_pct!=null?fmtPct(m.daily_loss_pct):'—'}/><Metric label="Exposure" value={m.exposure!=null?fmt(m.exposure):'—'}/><Metric label="Funding rate" value={f.rate!=null?fmtPct(f.rate):'—'}/><Metric label="Next funding" value={f.next_funding_time?new Date(f.next_funding_time).toLocaleTimeString():'—'}/><Metric label="Funding countdown" value={f.countdown_seconds!=null?fmtDuration(f.countdown_seconds):'—'}/><Metric label="Liq buffer" value={m.liquidation_buffer_pct!=null?fmtPct(m.liquidation_buffer_pct):'—'}/>{overview?.risk?.reasons?.map(x=><div className="alert danger" key={x}>{x}</div>)}</div>}
function Benchmark({mode,enabled=true}){const [rows,setRows]=useState([]);useEffect(()=>{if(!enabled)return;getJSON('/api/benchmarks?mode='+mode).then(x=>setRows(x.rows||[])).catch(()=>{})},[mode]);return <table><thead><tr><th>Benchmark</th><th>Return</th><th>Sharpe</th><th>DD</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.benchmark}</td><td>{r.total_return}</td><td>{r.sharpe}</td><td>{r.max_drawdown}</td></tr>)}</tbody></table>}
const fmt=v=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2});const fmtPct=v=>v==null?'—':(Number(v)*100).toFixed(2)+'%';const fmtDuration=v=>{v=Number(v);if(!Number.isFinite(v))return '—';const h=Math.floor(v/3600),m=Math.floor((v%3600)/60),sec=Math.floor(v%60);return `${h}h ${m}m ${sec}s`};const label=k=>k.replaceAll('_',' ')
function SkeletonFallback(){return <Skeleton/>} function LiveConfirm({onCancel,onConfirm}){return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><h2>Switch to LIVE?</h2><p>LIVE mode exposes production telemetry and may be associated with real execution. Confirm only after the go-live gate, human sign-off, IP whitelist and withdrawal-disabled key controls have been verified.</p><div className="modal-actions"><button onClick={onCancel}>Cancel</button><button className="danger-button" onClick={onConfirm}>Confirm LIVE</button></div></div></div>} const root=createRoot(document.getElementById('root'));root.render(<React.Suspense fallback={<SkeletonFallback/>}><App/></React.Suspense>)
